version: '3.9'

services:

  app:
    image: customer-service:latest
    build:
      context: .
    container_name: customer-service
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: "customer-service-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: customer-service-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    depends_on:
      - db
