version: '3.9'

services:

  app:
    image: customer-service:latest
    build:
      context: .
    container_name: customer-service
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: "customer-service-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - ./data:/var/lib/postgresql/data
    secrets:
      - pg_user
      - pg_password

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: customer-service-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    ports:
      - "8888:80"
    depends_on:
      - db
    secrets:
      - pgadmin_password

secrets:
  pg_user:
    file: ./pg_user.txt
  pg_password:
    file: ./pg_password.txt
  pgadmin_password:
    file: ./pgadmin_password.txt
