services:

  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "10"
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: logstash:8.15.1
    container_name: logstash
    volumes:
      - ./logstash-configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elastic_data:
    driver: local

networks:
  elk:
