services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ssl-generator

  ssl-generator:
    image: alpine:latest
    container_name: ssl-generator
    volumes:
      - ./certs:/certs
    entrypoint: /bin/sh -c "apk add --no-cache openssl bash && chmod +x /certs/generate_ssl.sh && /bin/bash /certs/generate_ssl.sh"
    environment:
      - CERT_DIR=/certs
